Repository mikesplain/mergetester, pull requests merged in 2021-06, with the labels that each got.

#5 Update README.md
  README.md
Labels: bug, documentation

#6 Update README.md
  README.md
Labels: bug

#12 Update README.md
  README.md
Labels: automerge
